defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/1_hyxmt.cn_bundle.crt"
      keyFile = "/ssl/2_hyxmt.cn.key"
      [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/1_shop.hyxmt.cn_bundle.crt"
      keyFile = "/ssl/2_shop.hyxmt.cn.key"