apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: traefik-ingress-lb
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      volumes:
      - name: ssl
        secret:
          secretName: my-hyxmt-cert-2019
      - name: config
        configMap:
          name: traefik-conf-hyxmt-https-2019
      hostNetwork: true
      restartPolicy: Always
      serviceAccountName: ingress
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/my-kubernets/traefik:1.7.10
        name: traefik-ingress-lb
        volumeMounts:
        - mountPath: /ssl
          name: ssl
        - mountPath: /config
          name: config
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: admin
          containerPort: 8591
          hostPort: 8591
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        args:
        - --configFile=/config/traefik-https.toml
        - --web
        - --web.address=:8591
        - --kubernetes