apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data-pvc
  namespace: tracking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: cassandra-data-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data-pv
  namespace: tracking
  labels:
    name: cassandra-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /share-data/cassandra/data
    server: 10.1.4.6

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-log-pvc
  namespace: tracking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: cassandra-log-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-log-pv
  namespace: tracking
  labels:
    name: cassandra-log-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /share-data/cassandra/logs
    server: 10.1.4.6