apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
  namespace: tracking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: elasticsearch-data-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv
  namespace: tracking
  labels:
    name: elasticsearch-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /share-data/elasticsearch
    server: 192.168.3.232